# ----------------------------
# Makefile Options
# ----------------------------

NAME = TUNDRA
ICON = icon.png
DESCRIPTION = "Tundra tilemap game"
COMPRESSED = NO
ARCHIVED = YES

CFLAGS = -Wall -Wextra -Oz
CXXFLAGS = -Wall -Wextra -Oz

# ----------------------------

include $(shell cedev-config --makefile)
